### ISSUE TITLE
I can't record and replay a route that use the method DELETE

### ISSUE THREAD

**Issue by FabienArcellier** [hiredscorelabs/cornell#12]
Hello,

I am trying to record the result of an API call that requires DELETE method. The script get a 405 error (method not allowed)
Have you blocked this behavior on purpose ? Can I propose a PR to add the support of this method ?

In `cornell/cornell_server.py` :

```python
SUPPORTED_METHODS = ['GET', 'POST', 'PUT']
```

**Comment by yaelmi3** [comment]
Didn't block it on purpose, just didn't encounter a use case, so far. Thanks for your addition.

**Comment by AvnerCohen** [comment]
Merged.

**Comment by FabienArcellier** [comment]
@yaelmi3 @AvnerCohen Thanks a lot for developping this idea. The result is really good :).
