### ISSUE TITLE
build a docker image for cornell

### ISSUE THREAD

**Issue by FabienArcellier** [hiredscorelabs/cornell#21]
In our development, we got stuck using `cornell` because one of our libraries didn't support Flask 2.0.0.

One solution would be to run cornell on an independent execution space. A docker image on dockerhub would solve this problem. I am preparing a PR to package a Dockerfile at the root of the repo.

I publish a repository in my own namespace. I have configured a rebuild every 24 hours. I will remove it as soon as you publish your own dockerhub repository.

```
docker run fabienarcellier/cornell
```

**Comment by look4regev** [comment]
Thanks @FabienArcellier . We've created a repo for that: https://hub.docker.com/repository/docker/hiredscorelabs/cornell. We'll soon set up a github action flow to upload to there the docker build image.

**Comment by look4regev** [comment]
Done: https://hub.docker.com/repository/docker/hiredscorelabs/cornell
(pipeline PR: https://github.com/hiredscorelabs/cornell/pull/23/files)

**Comment by FabienArcellier** [comment]
Great, I have removed mine
