### ISSUE TITLE
TypeError: get_custom_vcr() got multiple values for argument 'base_uri'

### ISSUE THREAD

**Issue by Wats0ns** [hiredscorelabs/cornell#25]
Hello,
it seems that running [this example](https://hiredscorelabs.github.io/cornell/docs/workflows/custom_matchers/) in the docs throws a `TypeError: get_custom_vcr() got multiple values for argument 'base_uri`

The problematic code is directly from the doc:
```python
#!/usr/bin/env python

import click
import json
from vcr.util import read_body
from cornell.cornell_server import CornellCmdOptions, start_cornell
from cornell.cornell_helpers import json_in_headers
from cornell.custom_matchers import requests_match_conditions


# Custom Matcher
@requests_match_conditions(json_in_headers, lambda request: request.body)
def vcr_json_custom_body_matcher(received_request, cassette_request):
    received_request_dict = json.loads(read_body(received_request))
    cassette_request_dict = json.loads(read_body(cassette_request))
    if received_request_dict == cassette_request_dict or "special_params" not in received_request_dict:
        return True
    return is_specially_matched(received_request_dict, cassette_request_dict)


@click.command(cls=CornellCmdOptions)
def start_mock_service(**kwargs):
    start_cornell(additional_vcr_matchers=[vcr_json_custom_body_matcher], **kwargs)


if __name__ == "__main__":
    start_mock_service()
```

Dockerfile to reproduce:
```dockerfile
FROM python:3.9-alpine

RUN pip install cornell
COPY cornell/main.py .
EXPOSE 9000

ENTRYPOINT ["python", "main.py"]
```

It seems that changing the line 189 in cornell_server.py to `    app.config.vcr = get_custom_vcr(app.config.base_uri, DUMMY_URL, record_errors,
                                    *additional_vcr_matchers)` fixes this, but it seems hacky. Overall I haven't been able to make the custom matchers work, anybody has a working example ? I'm looking to have a sidecar container that will record every request with same data parameters to an API, this seems like something cornell should do

**Comment by Wats0ns** [comment]
Hello @AvnerCohen, yes as stated in my previous message, this does work

**Comment by yaelmi3** [comment]
@Wats0ns , @AvnerCohen : I tend to agree that just removing the keywords is bit "hacky", please consider [this](https://github.com/hiredscorelabs/cornell/pull/26) fix

**Comment by AvnerCohen** [comment]
@Wats0ns Thanks for the report, this is now fixed in https://pypi.org/project/cornell/1.0.8/

@yaelmi3 👑
