### ISSUE TITLE
Support vcr.py >=5

### ISSUE THREAD

**Issue by cadlagtrader** [hiredscorelabs/cornell#28]
Not sure if this project is actively maintained, but it would be great to support recent versions of dependencies, such as vcr.py>=5

**Comment by yaelmi3** [comment]
Hi @cadlagtrader , [PR](https://github.com/hiredscorelabs/cornell/pull/29) was submitted

**Comment by AvnerCohen** [comment]
Updated, will soon publish https://github.com/hiredscorelabs/cornell/commit/f709a1303fcc86ff92858102d288831d893e383a
